# 텐서(TENSOR)

텐서(tensor)는 배열이나 행렬(metrix)와 매우 유사한 자료구조이다.
- 파이토치에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)한다.
- 텐서는 Numoy의 ndarray와 유사하다. 실제로 텐서는 Numpy배영과 동일한 내부 메모리를 공유할 수 있어 데이터를 복수할 필요가 없다.
- 텐서는 자동미분(automatic differentiation)에 최적화 되어있다.

In [1]:
import torch 
import numpy as np

### 텐서초기화
텐서 초기화 방법 (4가지)
- 데이터로부터 직접(directly) 생성하기
- Numpy 배열로부터 생성하기
- 다른 텐서로부터 생성하기
- 무작위(random) 또는 상수(constant)값을 사용하기

In [2]:
# 데이터로부터 직접(directly) 생성하기
data =[[1,2], [3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
# Numpy 배열로부터 생성하기
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np                    

tensor([[1, 2],
        [3, 4]])

In [4]:
# 다른 텐서로부터 생성하기
x_ones = torch.zeros_like(x_data) # 텐서의 shape은 유지, 값을 0로 바꿈
print(f"Zeros Tensor: \n {x_ones} \n")

x_ones = torch.ones_like(x_data) # 텐서의 shape은 유지, 값을 1로 바꿈
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # 텐서의 shape은 유지, 값을 random하게 바꿈
print(f"Random Tensor: \n {x_rand} \n")

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.1807, 0.2999],
        [0.5894, 0.8938]]) 



In [5]:
# 무작위(random) 또는 상수(constant)값을 사용하기
shape = (2,3,) # shape fix
rand_tensor = torch.rand(shape) # 랜덤
ones_tensor = torch.ones(shape) # 1
zeros_tensor = torch.zeros(shape) # 0

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0876, 0.6681, 0.3023],
        [0.5439, 0.6354, 0.9905]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서 연산(Operation)
- 전치, 인덱싱, 스리이싱, 수학 계산, 선형 대수, 임의 샘플링등, 100가지 이상의 텐서연산들이 있다. [텐서 연산 모음](https://pytorch.org/docs/stable/torch.html)
- 기본적으로 텐서는 CPU에 생성된다. .to()메소드를 사용하면 (GPU의 가용성을 확인한 뒤) GPU로 텐서를 명시적으로 이동 할 수 있다.


In [6]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

In [7]:
# Numpy식의 표준 인덱싱과 슬라이싱
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [8]:
# torch.cat()을 활용한 텐서 합치기
# torch.cat() vs torch.stack()
# cat()은 flatten하게 합치고 stack()은 쌓아올리듯 합친다.
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t1)
print(t2)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


In [9]:
# 산술 연산(Arithmetic operations)
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor) # shape만 일단 집어넣기
torch.matmul(tensor, tensor.T, out=y3) # elements 할당
print(f'y1: {y1}\ny2: {y2}\ny3: {y3}')


# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)
print(f'z1: {z1}\nz2: {z2}\nz3: {z3}')

y1: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y3: tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
z1: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z3: tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [10]:
# 단일-요소 텐서의 모든 값을 하나로 집계하여 요소가 하니인 텐서의 경우 item()을 사용하여 python숫자 값으로 변환가능
print(tensor)
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item), agg)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
12.0 <class 'float'> tensor(12.)


In [11]:
# in-place연산 결과를 operand에 저장하는 연산을 바꿔치기 연산이라고 부르며, 접미사 _를 갖는다.
print(tensor, "\n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


### Numpy 변환(Bridge)
CPU강의 텐서와 Numpy배열은 메모리 공간을 공유하기 때문데, 하나를 변경하면 다른 하나도 변경된다. 

In [12]:
# 텐서를 Numpy배열로 변환
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [13]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [14]:
# Numpy배열을 텐서로 변환
n = np.ones(5)
t = torch.from_numpy(n)

In [15]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
